import com.github.gradle.node.task.NodeTask
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.KotlinMultiplatform
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension
import java.net.URI

plugins {
    kotlin("multiplatform") version "2.3.0"
    id("com.vanniktech.maven.publish") version "0.36.0"
    id("org.jetbrains.dokka") version "2.1.0"
    id("com.github.node-gradle.node") version "7.1.0"
    kotlin("plugin.power-assert") version "2.3.0"
}

repositories {
    mavenCentral()
}

kotlin {
    explicitApi()
    js {
        browser {
            testTask {
                useKarma {}
            }
            commonWebpackConfig {
                sourceMaps = true
            }
        }
        compilerOptions {
            target = "es2015"
        }
    }
    sourceSets {
        jsTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(npm("puppeteer", "24.36.0"))
            }
        }
    }
}

@OptIn(ExperimentalKotlinGradlePluginApi::class)
powerAssert {
    functions = listOf("kotlin.assert", "kotlin.test.assertTrue", "kotlin.test.assertEquals", "kotlin.test.assertNull")
}

dokka {
    dokkaPublications.html {
        moduleName = project.name
        moduleVersion = project.version.toString()
        outputDirectory = layout.buildDirectory.dir("docs/html")
    }
    dokkaSourceSets.configureEach {
        sourceLink {
            remoteUrl = URI("https://github.com/sparky983/komponent/tree/main")
            remoteLineSuffix = "#L"
        }
    }
}

mavenPublishing {
    configure(KotlinMultiplatform(javadocJar = JavadocJar.Dokka("dokkaGenerate")))
    signAllPublications()
    publishToMavenCentral()
}

node {
    download.set(true)
    version.set("22.0.0")
    npmInstallCommand.set("ci")
}

val exportWebref by tasks.registering(NodeTask::class) {
    description = "Export Webref element and IDL data"
    dependsOn(tasks.named("npmInstall"))
    inputs.files("package.json", "package-lock.json", "buildSrc/src/main/js/export-webref.mjs")
    outputs.file(layout.buildDirectory.file("generated/webref/elements.json"))
    script.set(file("buildSrc/src/main/js/export-webref.mjs"))
}

tasks.register<Task>("generate") {
    description = "Generate node API"
    dependsOn(exportWebref)

    doLast {
        generate(
            layout.buildDirectory.file("generated/webref/elements.json").get().asFile,
            file("src/jsMain/kotlin/me/sparky983/komponent/generated"),
        )
    }
}

val verifyGenerated by tasks.registering {
    description = "Verify that generated tags.kt is up-to-date"
    dependsOn(exportWebref)
    doLast {
        val output = layout.buildDirectory.dir("generated/verification").get().asFile
        generate(layout.buildDirectory.file("generated/webref/elements.json").get().asFile, output)
        val expected = output.resolve("tags.kt").readText()
        val actual = file("src/jsMain/kotlin/me/sparky983/komponent/generated/tags.kt").readText()
        check(actual == expected) { "tags.kt is stale" }
    }
}

tasks.named("check") { dependsOn(verifyGenerated) }

plugins.withType<YarnPlugin> {
    rootProject.the<YarnRootExtension>().ignoreScripts = false
}
