import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import java.io.File

@Serializable
data class WebrefData(val source: Sources, val elements: List<ElementDefinition>)
@Serializable
data class Sources(val elements: String, val idl: String)
@Serializable
data class ElementDefinition(
    val name: String,
    val namespace: String,
    val `interface`: String? = null,
    val href: String,
    val obsolete: Boolean = false,
    val void: Boolean = false,
    val attributes: List<AttributeDefinition> = emptyList(),
    val events: List<EventDefinition> = emptyList(),
)

@Serializable
data class AttributeDefinition(
    val name: String,
    val parameter: String,
    val type: String,
    val obsolete: Boolean = false,
)
@Serializable
data class EventDefinition(val name: String, val parameter: String, val type: String)

private val kotlinKeywords = setOf(
    "as",
    "break",
    "class",
    "continue",
    "do",
    "else",
    "false",
    "for",
    "fun",
    "if",
    "in",
    "interface",
    "is",
    "null",
    "object",
    "package",
    "return",
    "super",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "typeof",
    "val",
    "var",
    "when",
    "while",
    "by",
    "catch",
    "constructor",
    "delegate",
    "dynamic",
    "field",
    "file",
    "finally",
    "get",
    "import",
    "init",
    "param",
    "property",
    "receiver",
    "set",
    "setparam",
    "where",
    "actual",
    "abstract",
    "annotation",
    "companion",
    "const",
    "crossinline",
    "data",
    "enum",
    "expect",
    "external",
    "final",
    "infix",
    "inline",
    "inner",
    "internal",
    "lateinit",
    "noinline",
    "open",
    "operator",
    "out",
    "override",
    "private",
    "protected",
    "public",
    "reified",
    "sealed",
    "suspend",
    "tailrec",
    "vararg",
    "value",
)

private fun identifier(value: String): String = if (value in kotlinKeywords) "`$value`" else value

private fun returnType(element: ElementDefinition): String {
    val interfaceName = element.`interface` ?: return "org.w3c.dom.Element"
    val unavailableHtmlInterfaces = setOf(
        "HTMLFencedFrameElement", "HTMLGeolocationElement", "HTMLModelElement",
        "HTMLPortalElement", "HTMLSelectedContentElement",
    )
    return when (element.namespace) {
        "html" -> if (interfaceName.startsWith("HTML") && interfaceName !in unavailableHtmlInterfaces) interfaceName else "HTMLElement"
        "svg" -> if (interfaceName == "SVGSVGElement") interfaceName else "SVGElement"
        else -> "org.w3c.dom.Element"
    }
}

private fun parentNamespace(element: ElementDefinition): String = when (element.namespace) {
    "svg" -> if (element.name == "svg") "Html" else "Svg"
    "mathml" -> if (element.name == "math") "Html" else "MathMl"
    else -> "Html"
}

private fun childNamespace(element: ElementDefinition): String = when (element.namespace) {
    "svg" -> "Svg"
    "mathml" -> "MathMl"
    else -> "Html"
}

private val json = Json { ignoreUnknownKeys = true }

@OptIn(ExperimentalSerializationApi::class)
fun generate(input: File, folder: File) {
    val definitions = input.inputStream().use {
        json.decodeFromStream<WebrefData>(it)
    }
    folder.mkdirs()
    folder.resolve("tags.kt").writeText(buildFile(definitions), Charsets.UTF_8)
}

private fun buildFile(data: WebrefData): String = buildString {
    appendLine("// Generated by buildSrc/src/main/kotlin/generate.kt; do not edit.")
    appendLine("@file:Suppress(\"PackageDirectoryMismatch\", \"unused\", \"LongParameterList\", \"RemoveExplicitTypeArguments\")")
    appendLine()
    appendLine("package me.sparky983.komponent")
    appendLine()
    appendLine("import kotlinx.browser.document")
    appendLine("import org.w3c.dom.*")
    appendLine("import org.w3c.dom.events.*")
    appendLine("import org.w3c.dom.svg.*")
    appendLine()
    appendLine("private typealias EventHandler<E> = (E) -> Unit")
    appendLine("private typealias Attributes = AttributesBuilder.() -> Unit")
    appendLine()
    appendLine("private fun <T : org.w3c.dom.Element, N : Namespace, C : Namespace> N.generatedTag(")
    appendLine("    domNode: T,")
    appendLine("    attributes: Map<String, Signal<String?>>,")
    appendLine("    data: Attributes?,")
    appendLine("    events: Map<String, EventHandler<*>?>,")
    appendLine("    emit: N.(Element<N, C>) -> Unit,")
    appendLine("    scope: (Element<N, C>, Contexts) -> C,")
    appendLine("    children: C.() -> Unit,")
    appendLine("): T {")
    appendLine("    val tag = Tag<N, C>(domNode)")
    appendLine("    fun subscribe(attribute: String, signal: Signal<String?>) {")
    appendLine("        fun set(value: String?) {")
    appendLine("            if (value != null) {")
    appendLine("                domNode.setAttribute(attribute, value)")
    appendLine("            } else {")
    appendLine("                domNode.removeAttribute(attribute)")
    appendLine("            }")
    appendLine("        }")
    appendLine("        val subscription = signal.subscribe(::set)")
    appendLine("        subscription.canceled = true")
    appendLine("        tag.onMount {")
    appendLine("            if (subscription.canceled) {")
    appendLine("                set(signal.value)")
    appendLine("            }")
    appendLine("            subscription.canceled = false")
    appendLine("        }")
    appendLine("        tag.onUnmount {")
    appendLine("            subscription.canceled = true")
    appendLine("        }")
    appendLine("    }")
    appendLine("    for ((name, signal) in attributes) {")
    appendLine("        subscribe(name, signal)")
    appendLine("    }")
    appendLine("    if (data != null) {")
    appendLine("        for ((attribute, signal) in AttributesBuilder().apply(data).attributes) {")
    appendLine("            subscribe(\"data-${'$'}attribute\", signal)")
    appendLine("        }")
    appendLine("    }")
    appendLine("    for ((name, handler) in events) if (handler != null) {")
    appendLine("        domNode.addEventListener(name, handler.unsafeCast<(Event) -> Unit>())")
    appendLine("    }")
    appendLine("    scope(tag, contexts).children()")
    appendLine("    emit(tag)")
    appendLine("    return domNode")
    appendLine("}")
    appendLine()
    appendLine("private fun <T : org.w3c.dom.Element, N : Namespace> N.generatedVoidTag(")
    appendLine("    domNode: T,")
    appendLine("    attributes: Map<String, Signal<String?>>,")
    appendLine("    data: Attributes?,")
    appendLine("    events: Map<String, EventHandler<*>?>,")
    appendLine("    emit: N.(Element<N, Nothing>) -> Unit,")
    appendLine("): T {")
    appendLine("    val tag = Tag<N, Nothing>(domNode)")
    appendLine("    fun subscribe(attribute: String, signal: Signal<String?>) {")
    appendLine("        fun set(value: String?) {")
    appendLine("            if (value != null) {")
    appendLine("                domNode.setAttribute(attribute, value)")
    appendLine("            } else {")
    appendLine("                domNode.removeAttribute(attribute)")
    appendLine("            }")
    appendLine("        }")
    appendLine("        val subscription = signal.subscribe(::set)")
    appendLine("        subscription.canceled = true")
    appendLine("        tag.onMount {")
    appendLine("            if (subscription.canceled) {")
    appendLine("                set(signal.value)")
    appendLine("            }")
    appendLine("            subscription.canceled = false")
    appendLine("        }")
    appendLine("        tag.onUnmount {")
    appendLine("            subscription.canceled = true")
    appendLine("        }")
    appendLine("    }")
    appendLine("    for ((name, signal) in attributes) {")
    appendLine("        subscribe(name, signal)")
    appendLine("    }")
    appendLine("    if (data != null) {")
    appendLine("        for ((attribute, signal) in AttributesBuilder().apply(data).attributes) {")
    appendLine("            subscribe(\"data-${'$'}attribute\", signal)")
    appendLine("        }")
    appendLine("    }")
    appendLine("    for ((name, handler) in events) if (handler != null) {")
    appendLine("        domNode.addEventListener(name, handler.unsafeCast<(Event) -> Unit>())")
    appendLine("    }")
    appendLine("    emit(tag)")
    appendLine("    return domNode")
    appendLine("}")

    for (element in data.elements) {
        val parent = parentNamespace(element)
        val child = childNamespace(element)
        val type = returnType(element)
        val attributes = element.attributes.distinctBy { it.parameter }
        val events = element.events.distinctBy { it.parameter }
        val obsoleteAttributes = attributes.filter { it.obsolete }
        appendLine()
        if (obsoleteAttributes.isNotEmpty()) {
            appendLine("/**")
            for (attribute in obsoleteAttributes) {
                appendLine(
                    " * @param ${identifier(attribute.parameter)} an " +
                        "[obsolete markup attribute](https://html.spec.whatwg.org/multipage/obsolete.html)"
                )
            }
            appendLine(" */")
        }
        if (element.obsolete) {
            appendLine(
                "@Deprecated(\"Obsolete markup element. See ${
                    element.href.replace(
                        "\"",
                        "\\\""
                    )
                }\")"
            )
        }
        append("public fun $parent.${identifier(element.name.replace("-", "_"))}(")
        for (attribute in attributes) {
            appendLine()
            append("    ${identifier(attribute.parameter)}: Signal<${attribute.type}>? = null,")
        }
        for (event in events) {
            appendLine()
            append("    ${identifier(event.parameter)}: EventHandler<${event.type}>? = null,")
        }
        appendLine()
        append("    data: Attributes? = null,")
        if (!element.void) {
            appendLine()
            append("    children: $child.() -> Unit,")
        }
        appendLine()
        appendLine("): $type {")
        if (element.void) {
            appendLine("    return generatedVoidTag<$type, $parent>(")
        } else {
            appendLine("    return generatedTag<$type, $parent, $child>(")
        }
        val creation = when (element.namespace) {
            "svg" -> "document.createElementNS(\"http://www.w3.org/2000/svg\", \"${element.name}\")"
            "mathml" -> "document.createElementNS(\"http://www.w3.org/1998/Math/MathML\", \"${element.name}\")"
            else -> "document.createElement(\"${element.name}\")"
        }
        appendLine("        $creation as $type,")
        appendLine("        buildMap {")
        for (attribute in attributes) {
            val parameter = identifier(attribute.parameter)
            if (attribute.type == "String") {
                appendLine("            $parameter?.let { signal -> put(\"${attribute.name}\", signal) }")
            } else {
                val transform = if (attribute.type == "Boolean") {
                    "if (it) \"\" else null"
                } else {
                    "it.toString()"
                }
                appendLine("            $parameter?.let { signal -> put(\"${attribute.name}\", signal { $transform }) }")
            }
        }
        appendLine("        },")
        appendLine("        data,")
        appendLine("        mapOf(")
        for (event in events) appendLine("            \"${event.name}\" to ${identifier(event.parameter)},")
        appendLine("        ),")
        appendLine("        emit = { this.element.emit(it) },")
        if (!element.void) {
            appendLine("        scope = ::$child,")
            appendLine("        children = children,")
        }
        appendLine("    )")
        appendLine("}")
    }
}.replace("\n", System.lineSeparator())
